name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Nodejs
      uses: actions/setup-node@v2
    - run: npm ci
    - run: npm run lint

  test:
    
    runs-on: ${{ matrix.os }}
    
    env: 
      LUAJIT_SRC: ./.install/LuaJIT-${{ matrix.luajit-version }}/src
    
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [12.x, 14.x, 16.x]
        luajit-version: [2.0.5]
      
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Use LuaJIT-${{ matrix.luajit-version }}
      uses: leafo/gh-actions-lua@v8.0.0
      with:
        luaVersion: luajit-${{ matrix.luajit-version }}
    - run: npm ci
    - name: Generate bytecode instructions for ${{ matrix.luajit-version }}
      run: npm run gen:inst
    - run: npm test
